global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'trafficsimulationservice'
    static_configs:
      - targets: ['host.docker.internal:5351']
  - job_name: 'visualsimulation'
    static_configs:
      - targets: ['host.docker.internal:5042']
  - job_name: 'trafficcontrolservice'
    static_configs:
      - targets: ['host.docker.internal:5258']
  - job_name: 'finecollectionservice'
    static_configs:
      - targets: ['host.docker.internal:5352']
  - job_name: 'vehicleregistrationservice'
    static_configs:
      - targets: ['host.docker.internal:5236']